### ISSUE TITLE
Uncaught TypeError: object is not a function

### ISSUE THREAD

**Issue by photex** [mattsawyer77/atom-perforce#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.179.0
**System**: linux 3.16.7-7-desktop
**Thrown From**: [atom-perforce](https://github.com/mattsawyer77/atom-perforce) package, v0.2.0
### Stack Trace

Uncaught TypeError: object is not a function

```
At /home/gcollier/.atom/packages/atom-perforce/node_modules/node-perforce/index.js:126

TypeError: object is not a function
  at /home/gcollier/.atom/packages/atom-perforce/node_modules/node-perforce/index.js:126:21
  at /home/gcollier/.atom/packages/atom-perforce/node_modules/node-perforce/index.js:40:21
  at ChildProcess.exithandler (child_process.js:756:5)
  at ChildProcess.emit (events.js:119:17)
  at maybeClose (child_process.js:1013:16)
  at Socket.<anonymous> (child_process.js:1181:11)
  at Socket.emit (events.js:116:17)
  at Pipe.close (net.js:477:12)

```
### Commands

```
     -0:23.7 settings-view:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-perforce, v0.2.0

# Dev
No dev packages
```

**Comment by mattsawyer77** [comment]
Thanks for the bug report @photex but I haven't seen this issue occur on my system. Can you tell me the steps to reproduce the issue (including any p4 commands you had run from the command line, etc.)?

**Comment by gkaran** [comment]
This issue has occurred to me and a colleague as well. We both did nothing but install the plugin and try to open a directory that is under a perforce workspace.

When trying to do any action to any file (whether create, edit, delete) we got the above issue.

Could you please share the configuration under which this works in your system?

**Comment by photex** [comment]
Hi @mattsawyer77 I tried this on my macbook as well and also get this error. I opened the folder (the root of the project), selected a couple of files and eventually get this.

On both systems I don't have p4 in /usr/bin. On my linux machine it's ~/bin and on my macbook it's in /usr/local/bin.

This project uses a p4config file and P4CONFIG is set in ~/.zshenv on both systems.

**Comment by photex** [comment]
Here is the stacktrace from my macbook (just updated to atom-perforce 0.2.0 as well.

```
At /Users/gregory.collier/.atom/packages/atom-perforce/node_modules/node-perforce/index.js:126

TypeError: object is not a function
  at /Users/gregory.collier/.atom/packages/atom-perforce/node_modules/node-perforce/index.js:126:21
  at /Users/gregory.collier/.atom/packages/atom-perforce/node_modules/node-perforce/index.js:40:21
  at ChildProcess.exithandler (child_process.js:756:5)
  at ChildProcess.emit (events.js:119:17)
  at maybeClose (child_process.js:1013:16)
  at Socket.<anonymous> (child_process.js:1181:11)
  at Socket.emit (events.js:116:17)
  at Pipe.close (net.js:477:12)

```

**Comment by mattsawyer77** [comment]
That error didn't make any sense to me. Then I realized I had the wrong version of node-perforce specified in my package.json. That's corrected now. Please update and let me know if that fixes (or changes) your problem, @photex @gkaran !

**Comment by photex** [comment]
I definitely no longer get the error. Nothing else seems to happen though
so I think I can move on to the mundane details of configuration.

Cheers!

**Comment by gkaran** [comment]
Error is eliminated here as well. Consider this resolved.

Same as @photex though, I can't do nothing else. When I try to mark a file for edit I get the following:

> Perforce: Error: '\<workspace><file> ' CMD.EXE was started with the above path as current directory. UNC paths are not supported. Defaulting to windows directory. 

File does not get marked for edit as well (probably has to do with the above error).

I don't know whether that has to do with the plugin or my configuration though. Sadly windows (which I have to use in work environment) as not so flexible with paths...

If you believe this to be irrelevant, please by all means, consider this issue resolved when it comes to me.

**Comment by mattsawyer77** [comment]
@gkaran the plugin is not yet windows compatible. I'll close this issue and open a separate one for that.
