### ISSUE TITLE
Automatically check-out files during project search/replace

### ISSUE THREAD

**Issue by ghost** [mattsawyer77/atom-perforce#17]
This would a nice time saving feature.  Currently, I get "Perforce: cannot edit an unsaved file" when I try to do this with the latest atom-perforce release (1.2.2).

Thanks!

**Comment by mattsawyer77** [comment]
I don't think this is actually possible. If I find a way to do this, I'll reopen. 

In the meantime, @sergiom-sf, if you want a workaround, here are two possible methods:

**A. open from the terminal:**
1. in your terminal, go to your workspace
2. `find . -type f -exec grep -l 'search pattern' -exec p4 edit {} \;`
3. now you should be able to find/replace project-wide in Atom without warnings

**B. if you find yourself doing this very often, you can use a allwrite workspace:**
1. change your client from noallwrite to allwrite, and remove noclobber
2. `p4 sync -f`
   At this point your workspace files should all be read/write. When you're ready to create a changelist from files you've edited, you'd need to use the `p4 reconcile` command.

Hope this helps.
