### ISSUE TITLE
Project specific client

### ISSUE THREAD

**Issue by Flonker** [mattsawyer77/atom-perforce#25]
I would like to have project specific perforce configuration.
Is that possible?

If not, can it be future feature? :)

**Comment by mattsawyer77** [comment]
Can you describe what you mean? I already use the plugin in this way. In each of my p4 workspaces, I have a .p4config file containing the client name. And I have 1 Atom project for each p4 workspace.

**Comment by Flonker** [comment]
Hmm. That's exactly what I want.
I didn't see anything about that in the readme so I didn't know it was possible.

What do I need to do to make this work?
Just put a file named .p4config in the folder?
What should the file contain?

**Comment by mattsawyer77** [comment]
I assumed most p4 users already had a setup like this...but I am no expert in p4 to be sure!

In my ~/.zshrc (i.e. ~/.bashrc if you are a bash user), I have specified 

```
export P4CONFIG=.p4config
export P4PORT=<p4 hostname:port>
export P4USER=sawyer
export P4IGNORE=.p4ignore
```

Note that I do _not_ specify a P4CLIENT var globally here.

Then in each workspace root I have a .p4config file which looks like

```
P4PORT=<p4 hostname:port>
P4USER=sawyer
P4CLIENT=<client/workspace name>
```

(Actually unsure whether I need the P4PORT/P4USER here...)

Let me know if this doesn't help you.

**Comment by Flonker** [comment]
Well I'm using windows so that will not work.
rarely use p4 cli because we use p4v, the visual client.

I'll try to figure out how to do it in windows. Ofcourse, if you know how, maybe you can tell me. :)

**Comment by mattsawyer77** [comment]
I think this should help: http://www.perforce.com/perforce/doc.current/manuals/cmdref/envars.html
