### ISSUE TITLE
Perforce commands error out with Atom

### ISSUE THREAD

**Issue by vsriniva28** [mattsawyer77/atom-perforce#27]
Hi,

I downloaded the perforce plugin and restarted Atom to use it. I am however unable to use the plugin to edit/save/revert files. The CLI works just fine from the project directory. I get the below error when using p4 commands via the Atom editor:

/single is outside any known perforce workspace
/home/vsriniva/.atom/packages/atom-perforce/lib/atom-perforce.js:541 Error: Command failed: /bin/sh -c p4 -ztag opened  ./...
Client 'ah-vsriniva-maci' unknown - use 'client' command to create it.

My .bashrc file has the below:

export PATH=$HOME/local/bin:$PATH
export P4CONFIG=.p4config
export P4PORT=perforce:1666
export P4USER=vsriniva

My path variable has the location of p4. p4 info contains ah-vsriniva-maci as the client name

Any ideas on what could be going on?

Thanks!

**Comment by ghost** [comment]
You may need to make sure you're P4CLIENT is set correctly.  

If you run p4 client from a command line, what workspace/client does it say you have ? Is this as you expected (and would contain the file you are trying to check out?)

**Comment by vsriniva28** [comment]
My perforce client points to /my/working/folder and the file I am trying to check out is within /my/working/folder/project/src/file.js

The CLI works fine with this configuration if I give the entire path to the file I am trying to check out. I suspect the plugin uses the entire path of the file too?

**Comment by mattsawyer77** [comment]
@vsriniva28 out of curiosity, is your workspace root at a higher level than the root of your p4 client root?

**Comment by mattsawyer77** [comment]
@vsriniva28 also, you said

> Client 'ah-vsriniva-maci' unknown - use 'client' command to create it.

and

> p4 info contains ah-vsriniva-maci as the client name

it sounds like your CLI might not be setup fully, either. See http://www.perforce.com/perforce/doc.current/manuals/p4guide/chapter.configuration.html for more info on this.

Are you using OSX? If so, it's a known issues that Atom doesn't handle environment vars very well on the Mac unless you start atom from the terminal. My plugin attempts to work around this (in a sort of crude way) by sourcing .bashrc (if your shell is bash) or .zshrc (if your shell is zsh) then grabbing the necessary environment vars.

**Comment by mattsawyer77** [comment]
I'm working on a refactor of environment handling now, but my colleague (and unwitting beta tester) says it doesn't work on his machine. Hopefully I'll iron things out soon.

**Comment by artagnon** [comment]
I'm having the same issue. A straight `/bin/sh -c "p4 opened ./..."` works fine, so I'm puzzled about what could be wrong. By the way, I guess we should use a read-only indicator (there's atleast one such package already) in conjunction with this.

**Comment by artagnon** [comment]
> is your workspace root at a higher level than the root of your p4 client root

Yeah, the client root is //foo/bar/ while the workspace root is /.

> My plugin attempts to work around this (in a sort of crude way) by sourcing .bashrc (if your shell is bash) or .zshrc (if your shell is zsh) then grabbing the necessary environment vars

Wait, that's because the login shell is sh in OSX? Why do you need ENV vars? Isn't everything in the p4config?

**Comment by mattsawyer77** [comment]
Sorry for the super-delayed response. Unfortunately, because this package relies on shelling out to run p4 commands, and because atom doesn't seem to do this automatically well (https://github.com/atom/atom/issues/6956), I am inextricably linked to environment variables. I'm about to publish a significant refactor of environment handling (v1.6) that might help the issue. If it doesn't, please let me know, and in that case I'd like to open a more specifically targeted bug regarding the atom project root dir being at a higher level than the p4 client root (unless there are other ways to reproduce this problem that I'm unaware of).
