### ISSUE TITLE
When atom-perforce is enabled, the new tab behavior is disrupted.

### ISSUE THREAD

**Issue by simoneau** [mattsawyer77/atom-perforce#3]
Ctrl-shift-F for "Find in Project", type in a search term, and press enter. When the results come up, click on one of them. The file which opens replaces the contents of the Project Find Results tab rather than opening a new tab. If I disable atom-perforce and restart Atom, I no longer see this bug.

I'm seeing this on Windows 7 with Atom 0.187.0.

**Comment by simoneau** [comment]
This may be a consequence of issue #2.

**Comment by zimme** [comment]
I'm seeing the same issue on OS X Yosemite with atom 0.1.88.0 and saw it om 0.187.0 too. Version 0.9.1 of this package

**Comment by mattsawyer77** [comment]
I have a fix for this, will be up soon.

**Comment by zimme** [comment]
:+1:
