### ISSUE TITLE
Source .bash_profile on OS X

### ISSUE THREAD

**Issue by stewartlord** [mattsawyer77/atom-perforce#31]
Took me a while to figure out that you source .bashrc. On OS X the Terminal app sources .bash_profile so that is where most users put their environment variables (such as export P4CONFIG).

**Comment by stewartlord** [comment]
Did you already tackle this a while ago in https://github.com/mattsawyer77/atom-perforce/commit/9482b650046aa98a77329ee10a91a932fb7ab087 ?

**Comment by mattsawyer77** [comment]
@stewartlord yes, but just now published the updated package. I'm now reading -- if your shell is bash -- .profile, .bash_profile, and .bashrc (in that order, last one wins in case of duplicate var names).

**Comment by stewartlord** [comment]
Nice! Thanks Matt
