### ISSUE TITLE
Incorrectly invoke windows file handling when not in p4 repo

### ISSUE THREAD

**Issue by unional** [mattsawyer77/atom-perforce#33]
I use both git and p4 on my machine depends on what I'm working on.  When I'm in a p4 folder, it works fine. When I'm in a git folder, it keep popup the windows file handling dialog whenever I try to open and save file:

![screen shot 2015-11-09 at 11 16 27 am](https://cloud.githubusercontent.com/assets/3254987/11043835/82d7966e-86d3-11e5-9d0b-7a2cfaffbec2.png)

If I have set the default program for the extension (e.g. using sublime for `.js`), then sublime will be invoked and open the file every time I open/save the file on atom. :(

**Comment by mattsawyer77** [comment]
@unional This doesn't make any sense to me. If you disable the atom-perforce plugin, and restart atom, do you still see the problem?

**Comment by unional** [comment]
Yes. It happens whenever atom-perforce is re-enabled.

**Comment by mattsawyer77** [comment]
@unional I assume you meant "No", as in, the problem only occurs with atom-perforce enabled?

**Comment by unional** [comment]
Correct.  When I disable `atom-perforce`, it is working fine.  this means I have to manually disable `atom-perfroce`, restart atom (before restart the problem persist), and then work on git projects.  And then re-enable `atom-perforce` when I work on p4 projects.

**Comment by unional** [comment]
ok, I found the issue......it's quite a corner case. It issue comes from my file name: `p4.js`.  The popup appears whenever that tab is active.  The call to `atomPerforce.showClientName()` in L132 will invoke `cmd.exe /s /c p4 info` at my `src` directory containing the `p4.js`. So then, cmd.exe picked up the `p4.js` instead of `p4.exe` and invoke the file handling code.

It's a _bug_ in node_perforce.

**Comment by unional** [comment]
I have created a PR to fix the error when trying to run p4 command outside of the client root.

**Comment by unional** [comment]
FYI the cause of this has been fixed in `node-perforce`. Once a new version is available, this will not happen
