### ISSUE TITLE
Atom + Perforce plugin not working on Xubuntu

### ISSUE THREAD

**Issue by DusanMadar** [mattsawyer77/atom-perforce#39]
Perforce integration in `Atom 1.2.2` is not working on `Xubuntu (Ubuntu 14.04.3 LTS)` since recent updates. Unfortunately, I don't remember the exact version which introduced this. I updated the Perforce plugin at least two times recently.

Before it was working OK but only when Atom was launched from the command line.

Now it is not working at all, regardless of the way Atom is started (from command line or GUI). The version control icon is not present in the lower right corner.

**Comment by TheGoctor** [comment]
I'm getting the same issue in Windows 7 64-bit. I was able to fix it by rolling back to v.1.6.4.

**EDIT:**
Rolling back to 1.6.4 brought the version control icon back, but the console said I wasn't in a known workspace directory (I was). Rolling back to 1.6.2 restored full functionality.

**Comment by unional** [comment]
The version control icon was a false alarm. Fixed in latest build (my bad). Besides the icon, does it run correctly?  It is working for me on Win2012 R2

**Comment by unional** [comment]
@TheGoctor , There was an issue on the workspace that I tried to fix with `p4Info.currentDirectory.startsWith(p4Info.clientRoot)` instead of `{dir}.startsWith(p4Info.clientRoot)`. You having the issue on 1.6.6?

**Comment by TheGoctor** [comment]
On 1.6.6 I get this message in the console when I try to edit:

```
C:\p4root\path\to\dir is outside any known perforce workspace  C:\.atom\packages\atom-perforce\lib\atom-perforce.js:174 
```

Outside of the console message, there is no indication that the plugin is functioning at all. Rolling back to 1.6.2 without changing anything else works fine.

**Comment by unional** [comment]
What do you see on the p4Info?
It is likely that on ubuntu (or your environment) `p4Info.currentDirectory` and `p4Info.clientRoot` is not what expected on windows.

Do you have multiple P4CLIENT on your system?

**Comment by TheGoctor** [comment]
I have a single P4CLIENT on my system, all config settings are set through environment variables, and `p4 info` shows the following:

```
User name: mac
Client name: mac_work
Client host: MAC-PC
Client root: C:\p4root
Current directory: c:\p4root\path\to\dir
...
```

The only oddity I notice here is that the current directory has a lowercase drive letter, while the client root is uppercase. Perhaps this is what's different between `p4Info.currentDirectory` and `{dir}`?

**Comment by unional** [comment]
Yep, that's the issue.  Seems like different system behaves differently. In my system the are both lower case while the input (dir/openbufferfilepath/etc) are in uppercase.

Filing PR.

**Comment by unional** [comment]
@DusanMadar, do you know if what you experience is from the same problem?

**Comment by DusanMadar** [comment]
The problem in my case is: `Unable to save file: Permission denied`, on `Atom 1.2.3` with `atom-perforce 1.6.6`.
So it seems that perforce integration is not triggered. Also, using actions from menu `Packages > Perforce > ...` seems to have no effect at all.

I am on `Linux` and there is no difference in case of `current directory` and `client root` (both are lowercase) based on `p4 info` output. Though, `p4 info` states that `Case Handling: sensitive`.

I have two clients - one on my local machine and one on server. Therefore `p4` `user name` and `client name` are not equal.

**Comment by DusanMadar** [comment]
This is what fix the problem for me: http://dm295.blogspot.co.uk/2015/12/atom-editor-and-perforce-integration-on.html

**Comment by mattsawyer77** [comment]
thanks @DusanMadar . I had assumed most p4 users setup their environment this way anyway. But I will add some notes about this to the readme.
