### ISSUE TITLE
Checkout on save/modified

### ISSUE THREAD

**Issue by zimme** [mattsawyer77/atom-perforce#4]
Add support for automatically checkout on save and/or when buffer is modified

**Comment by mattsawyer77** [comment]
I really want this feature too. But I haven't figured out how to intercept the save event yet. So it would work ok if your p4 client is set to "allwrite" (not so much with "noallwrite").

**Comment by mattsawyer77** [comment]
For the curious, I've opened a forum discussion here: https://discuss.atom.io/t/intercept-onwillsave-or-some-other-save-event/15597

**Comment by zimme** [comment]
I took a look at the discussion and I'm thinking we might wanna implement this anyways but not turn it on by default.

I'm thinking as it's triggered before save we can still run p4 edit and then the file is open for edit when atom saves the file. BUT if the p4 edit fails for some reason we will still get the save error, which is why we don't wanna have this option as a default and add a note on this in the config/doc.

**Comment by zimme** [comment]
We'll have to call p4 edit synchronously probably

**Comment by mattsawyer77** [comment]
re: running this synchronously, I'd rather not risk locking up Atom with a potentially expensive network operation like this.

However, I will look into the possibility of auto-add or auto-edit when a buffer is modified.

**Comment by zimme** [comment]
That will work and maybe there's a way to run revert unchanged files when closing buffers or something.

i.e. checkout when modifying a buffer then revert if there isn't any change once you close the buffer?

**Comment by mattsawyer77** [comment]
not a bad idea: It wouldn't be difficult to just run p4 revert -a <filename> when a p4-opened buffer is closed.

**Comment by zimme** [comment]
:+1:

Would be nice to have some automagical workflow with perforce in atom :smile:

**Comment by mattsawyer77** [comment]
I'm very close to having this implemented. the snag I've run into is that when the file is loaded into the buffer, the onDidStopChanging event is fired, even though I have not modified the buffer yet. this might have something to do with vim-mode (which I use 100% of the time).

**Comment by zimme** [comment]
Try turning vim mode off and see if that's the culprit. If it is maybe you can just use a `firstRun` variable per buffer which gets set if vim mode is enabled.

If `firstRun` is set then don't run the "normal" `onDidStopChanging` code?

**Comment by mattsawyer77** [comment]
The onDidChange event turned out to be exactly what I needed. I have this working in my environment now. I just need an upstream PR to be merged, and then I will publish this feature.

**Comment by zimme** [comment]
:+1: Lets hope the PR gets merged quickly. Nice work :smile:

**Comment by mattsawyer77** [comment]
alright, this is in. I've tested it quite a bit in my environment, but that doesn't always mean much. let me know how it works for you guys!
