### ISSUE TITLE
High (and stuck) pending request count

### ISSUE THREAD

**Issue by unional** [mattsawyer77/atom-perforce#41]
![image](https://cloud.githubusercontent.com/assets/3254987/11314228/94e015e8-8f98-11e5-870d-45c01d3de7b2.png)

And it stays there

**Comment by mattsawyer77** [comment]
not sure what this is. can you elaborate?

**Comment by unional** [comment]
Arr, nevermind. Was trying to create an issue on `atom-typescript`
