### ISSUE TITLE
Not parsing workspace name correctly?

### ISSUE THREAD

**Issue by michalgm** [mattsawyer77/atom-perforce#51]
When I try to save (and use the auto-edit feature), I get the following error in the console: 

```
Error: Command failed: /bin/sh -c p4 -ztag opened  ./...
Client 'gregm' unknown - use 'client' command to create it.
```

when i run p4 info, i get: 

```
User name: gmichalec
Client name: gmichalec-gregm
Client host: gregm
...
```

so it seems that the plugin is getting thrown off by the dash in the client name?
Let me know if there's anything I can do to help debug this. I'm using version 1.7.0.
Thanks!

**Comment by unional** [comment]
My client name has dash too. That shouldn't be the problem

**Comment by unional** [comment]
Whats' the p4 client reported on atom (lower right corner)? You can also place a break point at https://github.com/mattsawyer77/atom-perforce/blob/master/lib/atom-perforce.js#L55
to find out.

**Comment by michalgm** [comment]
It looks like it is sending false to setStatusClient. I backed up one 
function, and outputted the value of p4Info:
{
caseHandling: "sensitive"
clientAddress: XXX
clientHost: "gregm"
clientName: "gregm"
clientUnknown.: "Client unknown."
currentDirectory: "/home/gmichalec/.atom/packages/atom-perforce/lib"
peerAddress: XXX
serverAddress: XXX
serverCertExpires: "Apr 6 18:43:02 2025 GMT"
serverDate: "2015/12/18 09:54:26 -0800 PST"
serverEncryption: "encrypted"
serverLicense: XXX
serverLicenseIp: XXX
serverRoot: "/home/perforce/p4root"
serverUptime: "5602:27:42"
serverVersion: "P4D/LINUX26X86_64/2014.2/1033284 (2015/04/01)"
serverid: "XXX"
userName: "gmichalec"
}

**Comment by unional** [comment]
I think the `currentDirectory` is where the problem is. It should be your code directory.

@mattsawyer77 has the `clientUnknown.` in there to begin with.  I don't know what it is and how it happens. :)

**Comment by michalgm** [comment]
sorry - that currentDirectory is set to "/home/gmichalec/.atom/packages/atom-perforce/lib" because that is what I was viewing at the time. When I view a file in my code path, that parameter is set as I would expect.

**Comment by unional** [comment]
In that case do you see the `clientUnknown.`? @mattsawyer77 check that to reject the p4client.

**Comment by michalgm** [comment]
Yes, `clientUnknown.: "Client unknown."`

**Comment by michalgm** [comment]
I was able to get this working correctly by adding 'P4CLIENT' to the envVarsToExtract array in atom-perforce.js. Is there a particular reason this was not included originally? Let me know if you'd like me to do make a Pull Request. Thanks!

``` javascript
envVarsToExtract = [
        'P4CLIENT',
        'P4CONFIG',
        'P4IGNORE',
        'P4PORT',
        'P4USER',
        'P4TICKETS',
        'P4PASSWD',
        'HOME'
    ]
```

**Comment by mattsawyer77** [comment]
@michalgm to my knowledge, most users set P4CLIENT via a .p4config file in the root of their perforce workspace. Do you only have 1 workspace on your machine? If not, how do you manage this env var? Nevertheless, I don't have a problem accepting a PR on this.

**Comment by michalgm** [comment]
Ok - just submitted a PR. Yeah, this is just how we do perforce where I 
work - no .p4config, just the P4CLIENT env var, which I manage by having 
in my .profile. Thanks so much for writing this - permission errors from 
editing unopened p4 files had been my bane!

**Comment by mattsawyer77** [comment]
@michalgm you're welcome! 

for future reference, you can `export P4CONFIG=.p4config` in your profile/bashrc/whatever and then use a .p4config file in the root of your workspace (which would contain `P4CLIENT=<client name>`). This file can contain just about any p4-related var. This is pretty much essential if you have multiple workspaces on your machine.
