### ISSUE TITLE
Don't error on not managed projects

### ISSUE THREAD

**Issue by PhiLhoSoft** [mattsawyer77/atom-perforce#55]
It is kind of related to #15. When I open a project that's not managed by Perforce, I see errors in the console. It is a minor issue, but I think it would be better if the package just shut off and disable itself on such project.
The error:
![atom-atom-perforce-notmanaged](https://cloud.githubusercontent.com/assets/1087902/12169513/3dea9094-b539-11e5-9707-886ef7b1dcd8.png)
In short, in textual form:

> Error: Command failed: C:\Windows\system32\cmd.exe /s /c "p4 -ztag opened  ./..."
> Path 'c:\SomePath\PhiLhoSoft\Web\Playground...' is not under client's root 'C:/Sources'.

where `C:/Sources`  is the value of P4ROOT.

At home, where I don't have Perforce at all (but the package is installed because I have synchronized my settings), I have another error.
Perhaps you can detect if there is a P4ROOT environment variable. If not, just disable the package. If so, check the value against the Project paths. If not matching, don't try to issue p4 commands there.

Note: I appreciate the package, far more complete than the primitive (but already useful) one in Brackets, even providing useful information to the tree-view (status modified / added, etc.). Thanks.

**Comment by unional** [comment]
That seems like a regression. I had a PR to fix that.  Let me check

**Comment by unional** [comment]
@mattsawyer77 , how do you update the CHANGELOG? Are you doing it manually?

**Comment by mattsawyer77** [comment]
@unional I use this tool: https://github.com/skywinder/github-changelog-generator

Basically I do the following: 

```
github_changelog_generator -t <your token goes here> -u <your username> -p atom-perforce
```

then I edit CHANGELOG.md, replacing the unknown version #s with the next version (apm patch increments the 3rd digit, apm minor increments the 2nd digit, and apm publish major increments the first digit. then I make that commit)

then

```
git push origin master
api publish patch
```

hope that helps.

**Comment by unional** [comment]
Done! :rose:

**Comment by unional** [comment]
@PhiLhoSoft , does the new version solve your problem?

**Comment by PhiLhoSoft** [comment]
Sorry for the delay, I waited to be able to test at home.
At work, the fix is effective, I no longer have an error when I have multiple projects (one under Perforce, the other not) opened.
At home (Windows 10), I still have errors, alas.
![atom-atom-perforce-noperforce](https://cloud.githubusercontent.com/assets/1087902/12222765/2808619a-b7c6-11e5-8ebb-d8438dba5d74.png)

> Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "p4 info  "(…)
> Unhandled promise rejection Object with error: Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "p4 info  "(…)

As said, p4 isn't installed at home, no P4 in environment, etc.

> // call p4 info to make sure perforce is available

Well, might I suggest that if there is no P4ROOT environment variable, this test can be skipped entirely? My goal is to avoid, if possible, to have red lines in my console... :smile:

**Comment by unional** [comment]
You are right. I forgot to consider that. :P

**Comment by unional** [comment]
@PhiLhoSoft , like you said, it is related to #15 and I think that's the best way to fix this issue.
@mattsawyer77 , what do you think? I don't want to make any big changes without your input. :rose:

**Comment by mattsawyer77** [comment]
If someone wants to implement #15 that would be cool. I'd like the see the PR for it before it's merged though.

**Comment by unional** [comment]
Close this for #58 "Don't error on not managed projects" is fixed.
