### ISSUE TITLE
How to Use?

### ISSUE THREAD

**Issue by mikehuebner** [mattsawyer77/atom-perforce#6]
Hello!

Maybe I'm just a bit lost, or missing something. But I am not getting checkouts to happen in the client although I have .p4config file that gives the editor the credentials. Maybe I am not exploring this enough, but where can I set up these for my workspaces?

**Comment by mattsawyer77** [comment]
@mikehuebner are you working on Windows, Mac, or Linux? I haven't done much testing in Windows for this plugin yet, unfortunately as that's not a platform I know much about these days. But you will need to make sure the directory that contains the p4 command is in your path.

**Comment by mikehuebner** [comment]
I'm working on Mac. My P4Config looks a bit something like this:

```
P4PORT=perforce.example.com:EXAMPLEPORT
P4CLIENT=example_user_name
P4USER=thatsme
P4PASSWD=PasswordExample
P4IGNORE=.p4ignore
```

**Comment by mattsawyer77** [comment]
@mikehuebner what do you see if you run `p4 info` from the folder you've added to atom as the project root?

**Comment by mikehuebner** [comment]
Its based off of that root and not your workspace root? Interesting, that would make sense I guess. I have it set up one directory behind that, I thought Atom would pick up that I'm working in that file and that is my workspace. Not the parent folder.

**Comment by mattsawyer77** [comment]
Well not exactly. If you attempt to p4 edit a file via the plugin, for example, it will attempt to execute first p4 info (to make sure perforce is accessible), then p4 edit, both from the directory containing the file.

**Comment by mikehuebner** [comment]
`p4 info` is not accessible from my Workspace root folder. From the workspace sub folder I'm working it, its perfectly fine because that contains the `p4config` file.

**Comment by mattsawyer77** [comment]
As far as I can tell, this shouldn't be a problem. But can you confirm this for me:
case A (your Atom workspace root is above the directory containing .p4config):
1. open a file (somewhere within your p4 client tree) in atom that is not p4 opened yet
2. via the command palette or keymap: p4 edit

and/or 

case B: (your Atom workspace root contains a valid .p4config file):
same steps as above

If neither case succeeds, there might be some other issue in your environment (i.e. maybe the p4 command is not found in your $PATH). If case A fails but case B succeeds, I will open a bug to track this issue, because it would imply that the commands aren't being executed in the immediate parent directory of the given file.

**Comment by mikehuebner** [comment]
Opened up a directory with the p4 items in place.
![image](https://cloud.githubusercontent.com/assets/6125123/6952338/148acbec-d876-11e4-972f-a7c99c9150f7.png)

Something in the repo that hasn't been checked out yet:
![image](https://cloud.githubusercontent.com/assets/6125123/6952355/2b5eb4c8-d876-11e4-980d-08fbb143b0da.png)

Within the GUI (after a refresh) running `p4 edit` from the command palette, with no result.
![image](https://cloud.githubusercontent.com/assets/6125123/6952404/7f789a42-d876-11e4-8182-945e7f5fde02.png)

It doesn't seem like any of the commands are working, so I will try redirecting the workspace to the folder (for the sake of this testing).

---

Redirected from workspace to root of project.
Restarted Atom (just in case)
Ran the exact same steps, to no result.

The thing is it works fine in Sublime [https://github.com/ericmartel/Sublime-Text-3-Perforce-Plugin], but I've been wanting to work with Atom, sadly cannot work without P4.

**Comment by mattsawyer77** [comment]
is the p4 command in your path? and can you run p4 info from the folder containing .p4config?

**Comment by mikehuebner** [comment]
If I run p4 info from that directory it returns everything perfectly fine. My path is set up and all.

**Comment by mattsawyer77** [comment]
OK. Can you open the developer tools in Atom (option+cmd+i) then reload Atom (ctrl+option+cmd+l), open a file that is in your p4 client area, and try to do p4 edit in Atom. If anything goes wrong it should be logged to the console.

**Comment by mikehuebner** [comment]
Found some issues, but they don't make sense. This is with my workspace root in this folder for the project.

So root being `workspace/project_folder/`

![image](https://cloud.githubusercontent.com/assets/6125123/6953492/8a49faa8-d87e-11e4-8b40-d8c6e59a80d5.png)

**Comment by mattsawyer77** [comment]
It looks like the p4 command is not found on your path after all (I need to display a helpful error message for this). FYI to determine your path (because node might not be started from the terminal), the plugin uses a command that is essentially this:

``` sh
$SHELL -lc export | grep ^PATH
```

if you run this from your terminal, do you see the folder that contains p4 in the path? If not you'll need to add it to your .bashenv, .zshenv, or whatever environment file you use. And when I fix #5 that should help as well.

If so, I wonder if your default shell is somehow different than the one you're using now. 

Also, if you've aliased the p4 command that will not work FYI.

**Comment by mikehuebner** [comment]
That is strange, since the sublime setup works 100% fine, no problems at all. I'll take a look at a few things on my side and see if I can't make this more robust for a user to just use P4Config (of course with in the insane process of p4 installed).

**Comment by mattsawyer77** [comment]
4 things:
1. I have some code to make sure /usr/local/bin (the default p4 install location) is in the path, but I don't think this code ever gets called, I will fix that.
2. When I implement #5, users with problems like these can manually specify the path to the p4 executable.
3. I will add some info to the README to cut down on confusion.
4. I'll add an error notification for when the p4 executable is not found.

**Comment by mikehuebner** [comment]
I'm back to cause more problems! :dancer: 
Working in Atom again due to the 1.0 release, thought I would give it another shot. And using perforce, this is still not being friendly /:
Now getting an error that claims I have the wrong client, 
`Client 'Mikes-MacBook-Air' unknown - use 'client' command to create it.` But that is the name of my computer... So trying to debug this slowly and see if I can't get this working. I cannot seem to figure out why it would be claiming that to be the client. My P4Config says something completely different...

**Comment by mattsawyer77** [comment]
Can you verify which version of atom-perforce you have? 

Also, you might try adding these into your ~/.bashrc or ~/.zshrc:

```
export P4CONFIG=.p4config
export P4PORT=<your p4 server and port>
export P4USER=<your username>
```

**Comment by mattsawyer77** [comment]
FYI some of the p4 commands are executed from the root dirs of your atom project. That could be the real issue here.

**Comment by mikehuebner** [comment]
I've been using my `.bash_profile` to store my env vars. And I'll take a look, I can still execute P4 from the root so I'll take a look.

**Comment by mikehuebner** [comment]
![image](https://cloud.githubusercontent.com/assets/6125123/8862185/90a42770-3143-11e5-9ac7-3f485634c55e.png)
This is what I'm seeing, just for reference.

**Comment by mikehuebner** [comment]
I put the `exports` in a `.bashrc` and it isn't giving me an error. But still not checking out the files, let me keep checking I'll let you know.

**Comment by mikehuebner** [comment]
Still getting the same error, sadly.

**Comment by mattsawyer77** [comment]
Does `p4 info`, when run from the root directory of your atom project, give you the expected client name?

**Comment by mikehuebner** [comment]
This is what I get back

```
Client name: PROJECT_WORKSPACE_NAME
Client host: Mikes-MacBook-Air.local
Client root: /Users/mikehuebner/Workspace/_PROJECT
Client stream: //WORKSPACE_NAME/mainline
```

**Comment by mattsawyer77** [comment]
Did you restart (or reload) Atom after changing your .bashrc? After that, I'm curious what happens when you try the Edit or Sync commands. Anything useful in your console?

**Comment by mikehuebner** [comment]
If I manually open it for edit it works, if I just save it. It doesn't. Is that expected behavior if so the .bashrc fix worked. I'm wondering how I can get this edit to happen on save.

**Comment by mikehuebner** [comment]
Ah I see it, everything works! `.bashrc` is the solution! Sorry for the trouble!

**Comment by mattsawyer77** [comment]
FYI there is an auto-edit (and add and revert) setting in atom-perforce which will run p4 edit for you when you modify a file that isn't checked out.
