### ISSUE TITLE
Rename package to perforce

### ISSUE THREAD

**Issue by zimme** [mattsawyer77/atom-perforce#9]
How about skipping the atom- in the package name?

**Comment by mattsawyer77** [comment]
Not sure it's worth the effort. Also, I like having the Github repo (which I definitely don't want to rename to "perforce") have the same name as the package.

**Comment by zimme** [comment]
Np, I just felt the "atom-" part in the name felt a but redundant. I feel `perforce` as the package name in package.js file specified with the `name` option and use `atom-perforce` for the github project and folder name is good.

But it's personal preference and I can respect that.
